2025-02-28 14:06:50,605 [INFO] worker: 启动队列监控系统，并发工作进程数: 3
2025-02-28 14:06:50,638 [INFO] worker: 初始找到 2 个队列: image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_generation_973498d440494576a0e7a9ae2d9c532a
2025-02-28 14:06:50,642 [INFO] worker: 已启动工作进程 worker-1-a4d8b1b3 (PID: 45359)
2025-02-28 14:06:50,643 [INFO] worker: 已启动工作进程 worker-2-6c70b920 (PID: 45360)
2025-02-28 14:06:50,644 [INFO] worker: 已启动工作进程 worker-3-31c176b6 (PID: 45361)
2025-02-28 14:06:50,665 [INFO] worker: 发现 2 个新队列: image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_generation_973498d440494576a0e7a9ae2d9c532a
2025-02-28 14:06:50,665 [INFO] worker: 队列发生变化，重启所有工作进程以监听 2 个队列
2025-02-28 14:06:50,667 [INFO] worker: 已启动工作进程 worker-1-ef33b4f7 (PID: 45363)
2025-02-28 14:06:50,668 [INFO] worker: 已启动工作进程 worker-2-0c9b3163 (PID: 45364)
2025-02-28 14:06:50,670 [INFO] worker: 已启动工作进程 worker-3-782fc7c6 (PID: 45365)
2025-02-28 14:06:50,739 [INFO] worker: 工作进程 worker-2-0c9b3163 (PID: 45364) 开始监听 2 个队列
2025-02-28 14:06:50,740 [INFO] worker: 工作进程 worker-3-782fc7c6 (PID: 45365) 开始监听 2 个队列
2025-02-28 14:06:50,740 [INFO] worker: 工作进程 worker-1-ef33b4f7 (PID: 45363) 开始监听 2 个队列
2025-02-28 14:06:50,743 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-2-0c9b3163 started with PID 45364, version 1.14.1
2025-02-28 14:06:50,743 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-2-0c9b3163
2025-02-28 14:06:50,743 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-ef33b4f7 started with PID 45363, version 1.14.1
2025-02-28 14:06:50,743 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-ef33b4f7
2025-02-28 14:06:50,744 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-3-782fc7c6 started with PID 45365, version 1.14.1
2025-02-28 14:06:50,744 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-3-782fc7c6
2025-02-28 14:06:50,744 [INFO] rq.worker: *** Listening on image_generation_973498d440494576a0e7a9ae2d9c532a, image_generation_1ad9af0537c04c7481f3246d9ea75f08...
2025-02-28 14:06:50,744 [INFO] rq.worker: *** Listening on image_generation_973498d440494576a0e7a9ae2d9c532a, image_generation_1ad9af0537c04c7481f3246d9ea75f08...
2025-02-28 14:06:50,744 [INFO] rq.worker: *** Listening on image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_generation_973498d440494576a0e7a9ae2d9c532a...
2025-02-28 14:06:50,745 [INFO] rq.worker: Cleaning registries for queue: image_generation_973498d440494576a0e7a9ae2d9c532a
2025-02-28 14:06:50,745 [INFO] rq.worker: Cleaning registries for queue: image_generation_1ad9af0537c04c7481f3246d9ea75f08
2025-02-28 14:06:50,747 [INFO] rq.worker: image_generation_973498d440494576a0e7a9ae2d9c532a: app.services.queue.worker.process_image_task({'image_id': 231, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_973498d440494576a0e7a9ae2d9c532a_231_45753479deaf4e7ca6812206ed1d18c4)
2025-02-28 14:06:50,747 [INFO] rq.worker: image_generation_973498d440494576a0e7a9ae2d9c532a: app.services.queue.worker.process_image_task({'image_id': 232, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_973498d440494576a0e7a9ae2d9c532a_232_14b018dd397549ba99fa4bd0cb7f785c)
2025-02-28 14:06:50,747 [INFO] rq.worker: image_generation_1ad9af0537c04c7481f3246d9ea75f08: app.services.queue.worker.process_image_task({'image_id': 233, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_1ad9af0537c04c7481f3246d9ea75f08_233_67d214e6b8cd45e586908db7b00683f2)
2025-02-28 14:06:50,772 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=231
2025-02-28 14:06:50,772 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=232
2025-02-28 14:06:50,772 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=233
2025-02-28 14:06:50,923 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=233
2025-02-28 14:06:50,923 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=232
2025-02-28 14:06:50,923 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=231
2025-02-28 14:06:50,924 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_安卓数据线.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:06:50,924 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_wutu.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:06:50,924 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-微信-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:06:50,924 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_安卓数据线.png
2025-02-28 14:06:50,924 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-微信-500.png
2025-02-28 14:06:50,924 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_wutu.png
2025-02-28 14:06:50,932 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:06:50,933 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:06:50,936 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:06:51,897 [INFO] worker: 启动队列监控系统，并发工作进程数: 1
2025-02-28 14:06:51,926 [INFO] worker: 初始找到 2 个队列: image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_generation_973498d440494576a0e7a9ae2d9c532a
2025-02-28 14:06:51,930 [INFO] worker: 已启动工作进程 worker-1-cd77ee44 (PID: 45408)
2025-02-28 14:06:51,947 [INFO] worker: 发现 2 个新队列: image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_generation_973498d440494576a0e7a9ae2d9c532a
2025-02-28 14:06:51,947 [INFO] worker: 清理 3 个旧worker注册信息
2025-02-28 14:06:51,948 [INFO] worker: 队列发生变化，重启所有工作进程以监听 2 个队列
2025-02-28 14:06:51,949 [INFO] worker: 已启动工作进程 worker-1-184c6bda (PID: 45409)
2025-02-28 14:06:52,009 [INFO] worker: 工作进程 worker-1-184c6bda (PID: 45409) 开始监听 2 个队列
2025-02-28 14:06:52,013 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-184c6bda started with PID 45409, version 2.1.0
2025-02-28 14:06:52,013 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-184c6bda
2025-02-28 14:06:52,014 [INFO] rq.worker: *** Listening on image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_generation_973498d440494576a0e7a9ae2d9c532a...
2025-02-28 14:06:52,017 [INFO] rq.worker: image_generation_1ad9af0537c04c7481f3246d9ea75f08: app.services.queue.worker.process_image_task({'image_id': 232, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_1ad9af0537c04c7481f3246d9ea75f08_232_4bf982dd7ae446a1a1e48f8e46b8f1b1)
2025-02-28 14:06:52,028 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=232
2025-02-28 14:06:52,122 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=232
2025-02-28 14:06:52,123 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_wutu.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:06:52,123 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_wutu.png
2025-02-28 14:06:52,131 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:12,048 [INFO] worker: 发现 1 个新队列: image_generation_6e0196a6925f408da6fbaba44187dbd4
2025-02-28 14:07:12,050 [INFO] worker: 清理 1 个旧worker注册信息
2025-02-28 14:07:12,050 [INFO] worker: 队列发生变化，重启所有工作进程以监听 3 个队列
2025-02-28 14:07:12,051 [INFO] rq.worker: Worker wangjunyan.local:worker-1-184c6bda [PID 45409]: warm shut down requested
2025-02-28 14:07:13,055 [INFO] worker: 已启动工作进程 worker-1-335ee125 (PID: 45772)
2025-02-28 14:07:13,254 [INFO] worker: 工作进程 worker-1-335ee125 (PID: 45772) 开始监听 3 个队列
2025-02-28 14:07:13,261 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-335ee125 started with PID 45772, version 2.1.0
2025-02-28 14:07:13,261 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-335ee125
2025-02-28 14:07:13,262 [INFO] rq.worker: *** Listening on image_generation_973498d440494576a0e7a9ae2d9c532a, image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_generation_6e0196a6925f408da6fbaba44187dbd4...
2025-02-28 14:07:13,263 [ERROR] worker: 工作进程 worker-1-335ee125 (PID: 45772) 出错: daemonic processes are not allowed to have children
2025-02-28 14:07:16,621 [INFO] root: API调用成功，开始保存图片
2025-02-28 14:07:16,625 [INFO] root: 图片已保存到: uploads/c65493846f9c94488ade7fcf12c94ac8.png
2025-02-28 14:07:16,627 [INFO] app.services.queue.worker: 变体 1/3 生成成功: http://localhost:8002/uploads/c65493846f9c94488ade7fcf12c94ac8.png
2025-02-28 14:07:17,128 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=233
2025-02-28 14:07:17,129 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_安卓数据线.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:17,129 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_安卓数据线.png
2025-02-28 14:07:17,133 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:17,469 [INFO] root: API调用成功，开始保存图片
2025-02-28 14:07:17,471 [INFO] root: 图片已保存到: uploads/70c9192057a2c879dc853571154a40fa.png
2025-02-28 14:07:17,474 [INFO] app.services.queue.worker: 变体 1/3 生成成功: http://localhost:8002/uploads/70c9192057a2c879dc853571154a40fa.png
2025-02-28 14:07:17,975 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=232
2025-02-28 14:07:17,976 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_wutu.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:17,976 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_wutu.png
2025-02-28 14:07:17,979 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:20,750 [INFO] worker: 发现 1 个新队列: image_generation_6e0196a6925f408da6fbaba44187dbd4
2025-02-28 14:07:20,751 [INFO] worker: 清理 2 个旧worker注册信息
2025-02-28 14:07:20,751 [INFO] worker: 队列发生变化，重启所有工作进程以监听 3 个队列
2025-02-28 14:07:20,753 [INFO] rq.worker: Worker wangjunyan.local:worker-1-ef33b4f7 [PID 45363]: warm shut down requested
2025-02-28 14:07:21,753 [INFO] rq.worker: Worker wangjunyan.local:worker-2-0c9b3163 [PID 45364]: warm shut down requested
2025-02-28 14:07:22,754 [INFO] rq.worker: Worker wangjunyan.local:worker-3-782fc7c6 [PID 45365]: warm shut down requested
2025-02-28 14:07:23,080 [WARNING] worker: 工作进程 1 (PID: 45772) 已停止，重启中...
2025-02-28 14:07:23,082 [INFO] worker: 已重启工作进程 worker-1-5a41a425 (PID: 45937)
2025-02-28 14:07:23,180 [INFO] worker: 工作进程 worker-1-5a41a425 (PID: 45937) 开始监听 3 个队列
2025-02-28 14:07:23,184 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-5a41a425 started with PID 45937, version 2.1.0
2025-02-28 14:07:23,184 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-5a41a425
2025-02-28 14:07:23,184 [INFO] rq.worker: *** Listening on image_generation_973498d440494576a0e7a9ae2d9c532a, image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_generation_6e0196a6925f408da6fbaba44187dbd4...
2025-02-28 14:07:23,186 [INFO] rq.worker: Cleaning registries for queue: image_generation_6e0196a6925f408da6fbaba44187dbd4
2025-02-28 14:07:23,189 [INFO] rq.worker: image_generation_973498d440494576a0e7a9ae2d9c532a: app.services.queue.worker.process_image_task({'image_id': 230, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_973498d440494576a0e7a9ae2d9c532a_230_c8d4d3e7c8794365a9da49d37dfb291a)
2025-02-28 14:07:23,206 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=230
2025-02-28 14:07:23,335 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=230
2025-02-28 14:07:23,335 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_暂无图片-copy.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:23,336 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_暂无图片-copy.png
2025-02-28 14:07:23,344 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:23,756 [INFO] worker: 已启动工作进程 worker-1-d6ab93e2 (PID: 45939)
2025-02-28 14:07:23,758 [INFO] worker: 已启动工作进程 worker-2-a283659a (PID: 45940)
2025-02-28 14:07:23,759 [INFO] worker: 已启动工作进程 worker-3-bdead76e (PID: 45941)
2025-02-28 14:07:23,844 [INFO] worker: 工作进程 worker-2-a283659a (PID: 45940) 开始监听 3 个队列
2025-02-28 14:07:23,844 [INFO] worker: 工作进程 worker-3-bdead76e (PID: 45941) 开始监听 3 个队列
2025-02-28 14:07:23,844 [INFO] worker: 工作进程 worker-1-d6ab93e2 (PID: 45939) 开始监听 3 个队列
2025-02-28 14:07:23,848 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-2-a283659a started with PID 45940, version 1.14.1
2025-02-28 14:07:23,848 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-3-bdead76e started with PID 45941, version 1.14.1
2025-02-28 14:07:23,848 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-2-a283659a
2025-02-28 14:07:23,848 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-d6ab93e2 started with PID 45939, version 1.14.1
2025-02-28 14:07:23,848 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-3-bdead76e
2025-02-28 14:07:23,848 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-d6ab93e2
2025-02-28 14:07:23,849 [INFO] rq.worker: *** Listening on image_generation_6e0196a6925f408da6fbaba44187dbd4, image_generation_973498d440494576a0e7a9ae2d9c532a, image_generation_1ad9af0537c04c7481f3246d9ea75f08...
2025-02-28 14:07:23,849 [INFO] rq.worker: *** Listening on image_generation_973498d440494576a0e7a9ae2d9c532a, image_generation_6e0196a6925f408da6fbaba44187dbd4, image_generation_1ad9af0537c04c7481f3246d9ea75f08...
2025-02-28 14:07:23,849 [INFO] rq.worker: *** Listening on image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_generation_973498d440494576a0e7a9ae2d9c532a, image_generation_6e0196a6925f408da6fbaba44187dbd4...
2025-02-28 14:07:23,850 [INFO] rq.worker: Cleaning registries for queue: image_generation_6e0196a6925f408da6fbaba44187dbd4
2025-02-28 14:07:23,852 [INFO] rq.worker: image_generation_1ad9af0537c04c7481f3246d9ea75f08: app.services.queue.worker.process_image_task({'image_id': 231, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_1ad9af0537c04c7481f3246d9ea75f08_231_63a969e94f19495986a676a19be4e543)
2025-02-28 14:07:23,852 [INFO] rq.worker: image_generation_973498d440494576a0e7a9ae2d9c532a: app.services.queue.worker.process_image_task({'image_id': 229, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_973498d440494576a0e7a9ae2d9c532a_229_4befb8b2661443a88a993d6328591886)
2025-02-28 14:07:23,853 [INFO] rq.worker: image_generation_6e0196a6925f408da6fbaba44187dbd4: app.services.queue.worker.process_image_task({'image_id': 233, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_6e0196a6925f408da6fbaba44187dbd4_233_8e0eec762e364079b45c49fe4cc66ba0)
2025-02-28 14:07:23,867 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=233
2025-02-28 14:07:23,867 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=231
2025-02-28 14:07:23,867 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=229
2025-02-28 14:07:24,019 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=231
2025-02-28 14:07:24,020 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=229
2025-02-28 14:07:24,020 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=233
2025-02-28 14:07:24,020 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-微信-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:24,020 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-谷歌浏览器-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:24,020 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_安卓数据线.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:24,020 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-谷歌浏览器-500.png
2025-02-28 14:07:24,020 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-微信-500.png
2025-02-28 14:07:24,021 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_安卓数据线.png
2025-02-28 14:07:24,026 [INFO] root: 找到缓存的图片: uploads/c65493846f9c94488ade7fcf12c94ac8.png
2025-02-28 14:07:24,027 [INFO] app.services.queue.worker: 变体 1/3 生成成功: http://localhost:8002/uploads/c65493846f9c94488ade7fcf12c94ac8.png
2025-02-28 14:07:24,028 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:24,029 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:24,528 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=233
2025-02-28 14:07:24,528 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_安卓数据线.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:24,529 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_安卓数据线.png
2025-02-28 14:07:24,531 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:33,108 [INFO] worker: 有 1 个队列已移除: image_generation_973498d440494576a0e7a9ae2d9c532a
2025-02-28 14:07:33,109 [INFO] worker: 清理 8 个旧worker注册信息
2025-02-28 14:07:33,110 [INFO] worker: 队列发生变化，重启所有工作进程以监听 2 个队列
2025-02-28 14:07:33,110 [INFO] rq.worker: Worker wangjunyan.local:worker-1-5a41a425 [PID 45937]: warm shut down requested
2025-02-28 14:07:33,783 [INFO] worker: 有 1 个队列已移除: image_generation_973498d440494576a0e7a9ae2d9c532a
2025-02-28 14:07:33,783 [INFO] worker: 清理 1 个旧worker注册信息
2025-02-28 14:07:33,783 [INFO] worker: 队列发生变化，重启所有工作进程以监听 2 个队列
2025-02-28 14:07:33,784 [INFO] rq.worker: Worker wangjunyan.local:worker-1-d6ab93e2 [PID 45939]: warm shut down requested
2025-02-28 14:07:34,113 [INFO] worker: 已启动工作进程 worker-1-7c6b6d25 (PID: 46108)
2025-02-28 14:07:34,205 [INFO] worker: 工作进程 worker-1-7c6b6d25 (PID: 46108) 开始监听 2 个队列
2025-02-28 14:07:34,210 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-7c6b6d25 started with PID 46108, version 2.1.0
2025-02-28 14:07:34,210 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-7c6b6d25
2025-02-28 14:07:34,210 [INFO] rq.worker: *** Listening on image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_generation_6e0196a6925f408da6fbaba44187dbd4...
2025-02-28 14:07:34,213 [INFO] rq.worker: image_generation_1ad9af0537c04c7481f3246d9ea75f08: app.services.queue.worker.process_image_task({'image_id': 230, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_1ad9af0537c04c7481f3246d9ea75f08_230_f09347fca2b742cea9f1e498327a3cc6)
2025-02-28 14:07:34,226 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=230
2025-02-28 14:07:34,345 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=230
2025-02-28 14:07:34,345 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_暂无图片-copy.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:34,345 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_暂无图片-copy.png
2025-02-28 14:07:34,353 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:34,785 [INFO] rq.worker: Worker wangjunyan.local:worker-2-a283659a [PID 45940]: warm shut down requested
2025-02-28 14:07:35,787 [INFO] rq.worker: Worker wangjunyan.local:worker-3-bdead76e [PID 45941]: warm shut down requested
2025-02-28 14:07:36,789 [INFO] worker: 已启动工作进程 worker-1-809967ea (PID: 46143)
2025-02-28 14:07:36,790 [INFO] worker: 已启动工作进程 worker-2-d32161e2 (PID: 46144)
2025-02-28 14:07:36,791 [INFO] worker: 已启动工作进程 worker-3-ae27b7f5 (PID: 46145)
2025-02-28 14:07:36,879 [INFO] worker: 工作进程 worker-3-ae27b7f5 (PID: 46145) 开始监听 2 个队列
2025-02-28 14:07:36,879 [INFO] worker: 工作进程 worker-2-d32161e2 (PID: 46144) 开始监听 2 个队列
2025-02-28 14:07:36,880 [INFO] worker: 工作进程 worker-1-809967ea (PID: 46143) 开始监听 2 个队列
2025-02-28 14:07:36,883 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-2-d32161e2 started with PID 46144, version 1.14.1
2025-02-28 14:07:36,884 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-2-d32161e2
2025-02-28 14:07:36,884 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-809967ea started with PID 46143, version 1.14.1
2025-02-28 14:07:36,884 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-3-ae27b7f5 started with PID 46145, version 1.14.1
2025-02-28 14:07:36,884 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-809967ea
2025-02-28 14:07:36,884 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-3-ae27b7f5
2025-02-28 14:07:36,884 [INFO] rq.worker: *** Listening on image_generation_6e0196a6925f408da6fbaba44187dbd4, image_generation_1ad9af0537c04c7481f3246d9ea75f08...
2025-02-28 14:07:36,884 [INFO] rq.worker: *** Listening on image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_generation_6e0196a6925f408da6fbaba44187dbd4...
2025-02-28 14:07:36,884 [INFO] rq.worker: *** Listening on image_generation_6e0196a6925f408da6fbaba44187dbd4, image_generation_1ad9af0537c04c7481f3246d9ea75f08...
2025-02-28 14:07:36,887 [INFO] rq.worker: image_generation_6e0196a6925f408da6fbaba44187dbd4: app.services.queue.worker.process_image_task({'image_id': 232, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_6e0196a6925f408da6fbaba44187dbd4_232_e00a15b0da4d405ebd7d7295edf9c05f)
2025-02-28 14:07:36,887 [INFO] rq.worker: image_generation_6e0196a6925f408da6fbaba44187dbd4: app.services.queue.worker.process_image_task({'image_id': 231, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_6e0196a6925f408da6fbaba44187dbd4_231_8c8e79d7562f40ff9f0a2a0053747cec)
2025-02-28 14:07:36,887 [INFO] rq.worker: image_generation_1ad9af0537c04c7481f3246d9ea75f08: app.services.queue.worker.process_image_task({'image_id': 229, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_1ad9af0537c04c7481f3246d9ea75f08_229_2acef879b4ce4d2d93d32b56426b1552)
2025-02-28 14:07:36,901 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=232
2025-02-28 14:07:36,901 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=231
2025-02-28 14:07:36,901 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=229
2025-02-28 14:07:37,036 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=231
2025-02-28 14:07:37,036 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=229
2025-02-28 14:07:37,036 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=232
2025-02-28 14:07:37,037 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-微信-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:37,037 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-谷歌浏览器-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:37,037 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_wutu.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:37,037 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-微信-500.png
2025-02-28 14:07:37,037 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-谷歌浏览器-500.png
2025-02-28 14:07:37,037 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_wutu.png
2025-02-28 14:07:37,042 [INFO] root: 找到缓存的图片: uploads/70c9192057a2c879dc853571154a40fa.png
2025-02-28 14:07:37,043 [INFO] app.services.queue.worker: 变体 1/3 生成成功: http://localhost:8002/uploads/70c9192057a2c879dc853571154a40fa.png
2025-02-28 14:07:37,045 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:37,046 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:37,405 [INFO] root: API调用成功，开始保存图片
2025-02-28 14:07:37,407 [INFO] root: 图片已保存到: uploads/efc1222d71ed696e1df5e39723da6541.png
2025-02-28 14:07:37,410 [INFO] app.services.queue.worker: 变体 1/3 生成成功: http://localhost:8002/uploads/efc1222d71ed696e1df5e39723da6541.png
2025-02-28 14:07:37,544 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=232
2025-02-28 14:07:37,545 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_wutu.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:37,546 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_wutu.png
2025-02-28 14:07:37,550 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:37,910 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=229
2025-02-28 14:07:37,911 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-谷歌浏览器-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:37,911 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-谷歌浏览器-500.png
2025-02-28 14:07:37,913 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:44,143 [INFO] worker: 有 1 个队列已移除: image_generation_1ad9af0537c04c7481f3246d9ea75f08
2025-02-28 14:07:44,143 [INFO] worker: 清理 7 个旧worker注册信息
2025-02-28 14:07:44,144 [INFO] worker: 队列发生变化，重启所有工作进程以监听 1 个队列
2025-02-28 14:07:44,144 [INFO] rq.worker: Worker wangjunyan.local:worker-1-7c6b6d25 [PID 46108]: warm shut down requested
2025-02-28 14:07:45,148 [INFO] worker: 已启动工作进程 worker-1-d7cd041e (PID: 46282)
2025-02-28 14:07:45,245 [INFO] worker: 工作进程 worker-1-d7cd041e (PID: 46282) 开始监听 1 个队列
2025-02-28 14:07:45,249 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-d7cd041e started with PID 46282, version 2.1.0
2025-02-28 14:07:45,249 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-d7cd041e
2025-02-28 14:07:45,250 [INFO] rq.worker: *** Listening on image_generation_6e0196a6925f408da6fbaba44187dbd4...
2025-02-28 14:07:45,252 [INFO] rq.worker: image_generation_6e0196a6925f408da6fbaba44187dbd4: app.services.queue.worker.process_image_task({'image_id': 230, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_6e0196a6925f408da6fbaba44187dbd4_230_6f302d420b0d4b80b8c92445092ac979)
2025-02-28 14:07:45,263 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=230
2025-02-28 14:07:45,371 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=230
2025-02-28 14:07:45,372 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_暂无图片-copy.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:45,372 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_暂无图片-copy.png
2025-02-28 14:07:45,380 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:46,811 [INFO] worker: 有 1 个队列已移除: image_generation_1ad9af0537c04c7481f3246d9ea75f08
2025-02-28 14:07:46,812 [INFO] worker: 清理 2 个旧worker注册信息
2025-02-28 14:07:46,812 [INFO] worker: 队列发生变化，重启所有工作进程以监听 1 个队列
2025-02-28 14:07:46,813 [INFO] rq.worker: Worker wangjunyan.local:worker-1-809967ea [PID 46143]: warm shut down requested
2025-02-28 14:07:47,816 [INFO] rq.worker: Worker wangjunyan.local:worker-2-d32161e2 [PID 46144]: warm shut down requested
2025-02-28 14:07:48,815 [INFO] rq.worker: Worker wangjunyan.local:worker-3-ae27b7f5 [PID 46145]: warm shut down requested
2025-02-28 14:07:49,817 [INFO] worker: 已启动工作进程 worker-1-321b704f (PID: 46357)
2025-02-28 14:07:49,818 [INFO] worker: 已启动工作进程 worker-2-9594ac9d (PID: 46358)
2025-02-28 14:07:49,819 [INFO] worker: 已启动工作进程 worker-3-492a5981 (PID: 46359)
2025-02-28 14:07:49,903 [INFO] worker: 工作进程 worker-1-321b704f (PID: 46357) 开始监听 1 个队列
2025-02-28 14:07:49,903 [INFO] worker: 工作进程 worker-2-9594ac9d (PID: 46358) 开始监听 1 个队列
2025-02-28 14:07:49,903 [INFO] worker: 工作进程 worker-3-492a5981 (PID: 46359) 开始监听 1 个队列
2025-02-28 14:07:49,909 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-321b704f started with PID 46357, version 1.14.1
2025-02-28 14:07:49,909 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-2-9594ac9d started with PID 46358, version 1.14.1
2025-02-28 14:07:49,909 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-3-492a5981 started with PID 46359, version 1.14.1
2025-02-28 14:07:49,909 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-321b704f
2025-02-28 14:07:49,909 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-2-9594ac9d
2025-02-28 14:07:49,909 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-3-492a5981
2025-02-28 14:07:49,910 [INFO] rq.worker: *** Listening on image_generation_6e0196a6925f408da6fbaba44187dbd4...
2025-02-28 14:07:49,910 [INFO] rq.worker: *** Listening on image_generation_6e0196a6925f408da6fbaba44187dbd4...
2025-02-28 14:07:49,910 [INFO] rq.worker: *** Listening on image_generation_6e0196a6925f408da6fbaba44187dbd4...
2025-02-28 14:07:49,914 [INFO] rq.worker: image_generation_6e0196a6925f408da6fbaba44187dbd4: app.services.queue.worker.process_image_task({'image_id': 229, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) (image_generation_6e0196a6925f408da6fbaba44187dbd4_229_b8d2dc628a764db3a129ac8870e59d13)
2025-02-28 14:07:49,926 [INFO] app.services.queue.worker: 开始处理任务: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=229
2025-02-28 14:07:50,042 [INFO] app.services.queue.worker: 生成变体 1/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=229
2025-02-28 14:07:50,043 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-谷歌浏览器-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:50,043 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-谷歌浏览器-500.png
2025-02-28 14:07:50,048 [INFO] root: 找到缓存的图片: uploads/efc1222d71ed696e1df5e39723da6541.png
2025-02-28 14:07:50,048 [INFO] app.services.queue.worker: 变体 1/3 生成成功: http://localhost:8002/uploads/efc1222d71ed696e1df5e39723da6541.png
2025-02-28 14:07:50,550 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=229
2025-02-28 14:07:50,550 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-谷歌浏览器-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:07:50,551 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-谷歌浏览器-500.png
2025-02-28 14:07:50,555 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:07:55,173 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:07:55,173 [INFO] worker: 发现 2 个新队列: default, image_generation_default
2025-02-28 14:07:55,173 [INFO] worker: 有 1 个队列已移除: image_generation_6e0196a6925f408da6fbaba44187dbd4
2025-02-28 14:07:55,173 [INFO] worker: 清理 13 个旧worker注册信息
2025-02-28 14:07:55,174 [INFO] worker: 队列发生变化，重启所有工作进程以监听 2 个队列
2025-02-28 14:07:55,175 [INFO] rq.worker: Worker wangjunyan.local:worker-1-d7cd041e [PID 46282]: warm shut down requested
2025-02-28 14:07:56,177 [INFO] worker: 已启动工作进程 worker-1-8f19f317 (PID: 46467)
2025-02-28 14:07:56,260 [INFO] worker: 工作进程 worker-1-8f19f317 (PID: 46467) 开始监听 2 个队列
2025-02-28 14:07:56,264 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-8f19f317 started with PID 46467, version 2.1.0
2025-02-28 14:07:56,264 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-8f19f317
2025-02-28 14:07:56,265 [INFO] rq.worker: *** Listening on default, image_generation_default...
2025-02-28 14:07:56,266 [ERROR] worker: 工作进程 worker-1-8f19f317 (PID: 46467) 出错: daemonic processes are not allowed to have children
2025-02-28 14:07:59,861 [INFO] worker: 发现 1 个新队列: image_generation_default
2025-02-28 14:07:59,861 [INFO] worker: 有 1 个队列已移除: image_generation_6e0196a6925f408da6fbaba44187dbd4
2025-02-28 14:07:59,861 [INFO] worker: 清理 2 个旧worker注册信息
2025-02-28 14:07:59,862 [INFO] worker: 队列发生变化，重启所有工作进程以监听 1 个队列
2025-02-28 14:07:59,862 [INFO] rq.worker: Worker wangjunyan.local:worker-1-321b704f [PID 46357]: warm shut down requested
2025-02-28 14:07:59,865 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-321b704f
2025-02-28 14:07:59,987 [INFO] rq.worker: Worker wangjunyan.local:worker-2-9594ac9d [PID 46358]: warm shut down requested
2025-02-28 14:07:59,989 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-2-9594ac9d
2025-02-28 14:08:00,187 [INFO] rq.worker: Worker wangjunyan.local:worker-3-492a5981 [PID 46359]: warm shut down requested
2025-02-28 14:08:01,191 [INFO] worker: 已启动工作进程 worker-1-ee942dd1 (PID: 46539)
2025-02-28 14:08:01,193 [INFO] worker: 已启动工作进程 worker-2-4ba2f7ad (PID: 46540)
2025-02-28 14:08:01,194 [INFO] worker: 已启动工作进程 worker-3-01707113 (PID: 46541)
2025-02-28 14:08:01,291 [INFO] worker: 工作进程 worker-2-4ba2f7ad (PID: 46540) 开始监听 1 个队列
2025-02-28 14:08:01,291 [INFO] worker: 工作进程 worker-1-ee942dd1 (PID: 46539) 开始监听 1 个队列
2025-02-28 14:08:01,293 [INFO] worker: 工作进程 worker-3-01707113 (PID: 46541) 开始监听 1 个队列
2025-02-28 14:08:01,298 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-2-4ba2f7ad started with PID 46540, version 1.14.1
2025-02-28 14:08:01,298 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-ee942dd1 started with PID 46539, version 1.14.1
2025-02-28 14:08:01,298 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-2-4ba2f7ad
2025-02-28 14:08:01,298 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-ee942dd1
2025-02-28 14:08:01,299 [INFO] rq.worker: *** Listening on image_generation_default...
2025-02-28 14:08:01,299 [INFO] rq.worker: *** Listening on image_generation_default...
2025-02-28 14:08:01,299 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-3-01707113 started with PID 46541, version 1.14.1
2025-02-28 14:08:01,299 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-3-01707113
2025-02-28 14:08:01,300 [INFO] rq.worker: *** Listening on image_generation_default...
2025-02-28 14:08:01,301 [INFO] rq.worker: Cleaning registries for queue: image_generation_default
2025-02-28 14:08:06,202 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:08:06,202 [WARNING] worker: 工作进程 1 (PID: 46467) 已停止，重启中...
2025-02-28 14:08:06,204 [INFO] worker: 已重启工作进程 worker-1-3a6f5239 (PID: 46647)
2025-02-28 14:08:06,284 [INFO] worker: 工作进程 worker-1-3a6f5239 (PID: 46647) 开始监听 2 个队列
2025-02-28 14:08:06,288 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-3a6f5239 started with PID 46647, version 2.1.0
2025-02-28 14:08:06,288 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-3a6f5239
2025-02-28 14:08:06,289 [INFO] rq.worker: *** Listening on default, image_generation_default...
2025-02-28 14:08:06,290 [INFO] rq.worker: Cleaning registries for queue: default
2025-02-28 14:08:10,753 [INFO] root: API调用成功，开始保存图片
2025-02-28 14:08:10,757 [INFO] root: 图片已保存到: uploads/aa0b10c4a9454746bde4f399298efddd.png
2025-02-28 14:08:10,764 [INFO] app.services.queue.worker: 变体 2/3 生成成功: http://localhost:8002/uploads/aa0b10c4a9454746bde4f399298efddd.png
2025-02-28 14:08:11,220 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:08:11,220 [INFO] worker: 发现 1 个新队列: default
2025-02-28 14:08:11,220 [INFO] worker: 清理 11 个旧worker注册信息
2025-02-28 14:08:11,221 [INFO] worker: 队列发生变化，重启所有工作进程以监听 2 个队列
2025-02-28 14:08:11,221 [INFO] rq.worker: Worker wangjunyan.local:worker-1-ee942dd1 [PID 46539]: warm shut down requested
2025-02-28 14:08:11,222 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-ee942dd1
2025-02-28 14:08:11,266 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=232
2025-02-28 14:08:11,267 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_wutu.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:08:11,267 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_wutu.png
2025-02-28 14:08:11,270 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:08:11,362 [INFO] rq.worker: Worker wangjunyan.local:worker-2-4ba2f7ad [PID 46540]: warm shut down requested
2025-02-28 14:08:11,363 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-2-4ba2f7ad
2025-02-28 14:08:11,563 [INFO] rq.worker: Worker wangjunyan.local:worker-3-01707113 [PID 46541]: warm shut down requested
2025-02-28 14:08:11,564 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-3-01707113
2025-02-28 14:08:11,764 [INFO] worker: 已启动工作进程 worker-1-2de8bec1 (PID: 46718)
2025-02-28 14:08:11,766 [INFO] worker: 已启动工作进程 worker-2-770bd1d2 (PID: 46719)
2025-02-28 14:08:11,767 [INFO] worker: 已启动工作进程 worker-3-a9396012 (PID: 46720)
2025-02-28 14:08:11,852 [INFO] worker: 工作进程 worker-3-a9396012 (PID: 46720) 开始监听 2 个队列
2025-02-28 14:08:11,852 [INFO] worker: 工作进程 worker-2-770bd1d2 (PID: 46719) 开始监听 2 个队列
2025-02-28 14:08:11,852 [INFO] worker: 工作进程 worker-1-2de8bec1 (PID: 46718) 开始监听 2 个队列
2025-02-28 14:08:11,858 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-2de8bec1 started with PID 46718, version 1.14.1
2025-02-28 14:08:11,858 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-2de8bec1
2025-02-28 14:08:11,858 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-2-770bd1d2 started with PID 46719, version 1.14.1
2025-02-28 14:08:11,858 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-3-a9396012 started with PID 46720, version 1.14.1
2025-02-28 14:08:11,858 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-2-770bd1d2
2025-02-28 14:08:11,858 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-3-a9396012
2025-02-28 14:08:11,859 [INFO] rq.worker: *** Listening on image_generation_default, default...
2025-02-28 14:08:11,859 [INFO] rq.worker: *** Listening on default, image_generation_default...
2025-02-28 14:08:11,859 [INFO] rq.worker: *** Listening on image_generation_default, default...
2025-02-28 14:08:11,860 [INFO] rq.worker: Cleaning registries for queue: default
2025-02-28 14:08:16,230 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:08:21,798 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:08:26,427 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:08:31,826 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:08:36,451 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:08:37,777 [INFO] root: API调用成功，开始保存图片
2025-02-28 14:08:37,780 [INFO] root: 图片已保存到: uploads/8f7913ea7a6de8570115ba12f4fa393f.png
2025-02-28 14:08:37,782 [INFO] app.services.queue.worker: 变体 1/3 生成成功: http://localhost:8002/uploads/8f7913ea7a6de8570115ba12f4fa393f.png
2025-02-28 14:08:38,284 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=230
2025-02-28 14:08:38,285 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_暂无图片-copy.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:08:38,285 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_暂无图片-copy.png
2025-02-28 14:08:38,289 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:08:41,855 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:08:46,475 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:08:50,620 [INFO] root: API调用成功，开始保存图片
2025-02-28 14:08:50,623 [INFO] root: 图片已保存到: uploads/aa0b10c4a9454746bde4f399298efddd.png
2025-02-28 14:08:50,626 [INFO] app.services.queue.worker: 变体 2/3 生成成功: http://localhost:8002/uploads/aa0b10c4a9454746bde4f399298efddd.png
2025-02-28 14:08:51,127 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=232
2025-02-28 14:08:51,128 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_wutu.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:08:51,128 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_wutu.png
2025-02-28 14:08:51,132 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:08:51,878 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:08:56,505 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:09:01,906 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:09:05,469 [INFO] root: API调用成功，开始保存图片
2025-02-28 14:09:05,471 [INFO] root: 图片已保存到: uploads/1e059be7b940185608e8b1f9a2de8fa4.png
2025-02-28 14:09:05,473 [INFO] app.services.queue.worker: 变体 2/3 生成成功: http://localhost:8002/uploads/1e059be7b940185608e8b1f9a2de8fa4.png
2025-02-28 14:09:05,975 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=230
2025-02-28 14:09:05,976 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_暂无图片-copy.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:09:05,976 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_暂无图片-copy.png
2025-02-28 14:09:05,981 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:09:06,531 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:09:11,930 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:09:16,556 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:09:21,956 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:09:26,584 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:09:31,977 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:09:36,607 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:09:42,004 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:09:46,636 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:09:52,030 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:09:56,681 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:10:02,061 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:10:06,712 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:10:07,218 [INFO] root: API调用成功，开始保存图片
2025-02-28 14:10:07,221 [INFO] root: 图片已保存到: uploads/cff8707687aa3c9f67570aa968ad217b.png
2025-02-28 14:10:07,223 [INFO] app.services.queue.worker: 变体 3/3 生成成功: http://localhost:8002/uploads/cff8707687aa3c9f67570aa968ad217b.png
2025-02-28 14:10:07,225 [INFO] app.services.queue.worker: 任务完成: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=232, 生成了 3 个变体
2025-02-28 14:10:07,229 [INFO] rq.worker: Successfully completed app.services.queue.worker.process_image_task({'image_id': 232, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) job in 0:03:15.204083s on worker wangjunyan.local:worker-1-184c6bda
2025-02-28 14:10:07,229 [INFO] rq.worker: image_generation_1ad9af0537c04c7481f3246d9ea75f08: Job OK (image_generation_1ad9af0537c04c7481f3246d9ea75f08_232_4bf982dd7ae446a1a1e48f8e46b8f1b1)
2025-02-28 14:10:07,229 [INFO] rq.worker: Result is kept for 500 seconds
2025-02-28 14:10:07,235 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-184c6bda: stopping on request
2025-02-28 14:10:07,236 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-184c6bda
2025-02-28 14:10:12,090 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:10:16,738 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:10:22,116 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:10:26,826 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:10:32,150 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:10:36,854 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:10:42,179 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:10:46,875 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:10:52,201 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:10:56,900 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:11:02,228 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:11:06,930 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:11:12,255 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:11:16,956 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:11:22,281 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:11:26,981 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:11:27,176 [INFO] root: API调用成功，开始保存图片
2025-02-28 14:11:27,180 [INFO] root: 图片已保存到: uploads/e3e35eec332acd63dfe79cc19ca49593.png
2025-02-28 14:11:27,183 [INFO] app.services.queue.worker: 变体 2/3 生成成功: http://localhost:8002/uploads/e3e35eec332acd63dfe79cc19ca49593.png
2025-02-28 14:11:27,685 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=229
2025-02-28 14:11:27,686 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-谷歌浏览器-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:11:27,686 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-谷歌浏览器-500.png
2025-02-28 14:11:27,690 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:11:32,308 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:11:37,010 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:11:42,337 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:11:47,035 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:11:52,349 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:11:57,038 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:12:02,361 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:12:07,048 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:12:12,388 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:12:17,071 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:12:22,411 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:12:27,098 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:12:32,438 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:12:37,121 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:12:42,464 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:12:47,151 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:12:52,492 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:12:57,177 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:13:02,516 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:13:07,210 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:13:12,546 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:13:17,236 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:13:22,573 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:13:27,277 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:13:32,600 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:13:37,309 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:13:42,632 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:13:47,336 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:13:52,658 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:13:57,366 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:14:02,689 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:14:07,394 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:14:12,722 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:14:17,425 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:14:22,749 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:14:27,457 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:14:32,780 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:14:37,486 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:14:42,806 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:14:47,515 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:14:52,841 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:14:57,546 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:15:02,875 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:15:07,577 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:15:12,910 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:15:17,599 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:15:22,939 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:15:27,625 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:15:32,976 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:15:37,649 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:15:43,002 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:15:47,684 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:15:53,027 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:15:57,711 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:16:03,058 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:16:07,739 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:16:13,085 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:16:17,769 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:16:23,123 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:16:27,795 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:16:33,161 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:16:37,823 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:16:43,189 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:16:47,849 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:16:50,728 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:16:50,729 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:16:50,754 [ERROR] app.services.queue.worker: 生成变体 1/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:16:50,754 [ERROR] app.services.queue.worker: 生成变体 1/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:16:50,728 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:16:50,762 [ERROR] app.services.queue.worker: 生成变体 2/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:16:51,255 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=232
2025-02-28 14:16:51,256 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=231
2025-02-28 14:16:51,256 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_wutu.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:16:51,256 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-微信-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:16:51,256 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_wutu.png
2025-02-28 14:16:51,257 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-微信-500.png
2025-02-28 14:16:51,258 [INFO] root: 找到缓存的图片: uploads/e3e35eec332acd63dfe79cc19ca49593.png
2025-02-28 14:16:51,258 [INFO] root: 找到缓存的图片: uploads/aa0b10c4a9454746bde4f399298efddd.png
2025-02-28 14:16:51,258 [INFO] app.services.queue.worker: 变体 2/3 生成成功: http://localhost:8002/uploads/e3e35eec332acd63dfe79cc19ca49593.png
2025-02-28 14:16:51,258 [INFO] app.services.queue.worker: 变体 2/3 生成成功: http://localhost:8002/uploads/aa0b10c4a9454746bde4f399298efddd.png
2025-02-28 14:16:51,264 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=233
2025-02-28 14:16:51,264 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_安卓数据线.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:16:51,264 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_安卓数据线.png
2025-02-28 14:16:51,267 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:16:51,760 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=232
2025-02-28 14:16:51,760 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=231
2025-02-28 14:16:51,761 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_wutu.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:16:51,761 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-微信-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:16:51,761 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_wutu.png
2025-02-28 14:16:51,761 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-微信-500.png
2025-02-28 14:16:51,762 [INFO] root: 找到缓存的图片: uploads/cff8707687aa3c9f67570aa968ad217b.png
2025-02-28 14:16:51,762 [INFO] app.services.queue.worker: 变体 3/3 生成成功: http://localhost:8002/uploads/cff8707687aa3c9f67570aa968ad217b.png
2025-02-28 14:16:51,764 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:16:51,765 [INFO] app.services.queue.worker: 任务完成: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=232, 生成了 2 个变体
2025-02-28 14:16:51,789 [INFO] rq.worker: image_generation_973498d440494576a0e7a9ae2d9c532a: Job OK (image_generation_973498d440494576a0e7a9ae2d9c532a_232_14b018dd397549ba99fa4bd0cb7f785c)
2025-02-28 14:16:51,790 [INFO] rq.worker: Result is kept for 500 seconds
2025-02-28 14:16:51,801 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-2-0c9b3163: stopping on request
2025-02-28 14:16:51,802 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-2-0c9b3163
2025-02-28 14:16:53,216 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:16:57,875 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:17:03,239 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:17:07,901 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:17:13,261 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:17:17,928 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:17:23,146 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:17:23,166 [ERROR] app.services.queue.worker: 生成变体 1/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:17:23,283 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:17:23,668 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=230
2025-02-28 14:17:23,669 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_暂无图片-copy.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:17:23,670 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_暂无图片-copy.png
2025-02-28 14:17:23,671 [INFO] root: 找到缓存的图片: uploads/1e059be7b940185608e8b1f9a2de8fa4.png
2025-02-28 14:17:23,671 [INFO] app.services.queue.worker: 变体 2/3 生成成功: http://localhost:8002/uploads/1e059be7b940185608e8b1f9a2de8fa4.png
2025-02-28 14:17:23,817 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:17:23,839 [ERROR] app.services.queue.worker: 生成变体 2/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:17:23,817 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/models.py", line 836, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/models.py", line 758, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:17:23,817 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:17:23,858 [ERROR] app.services.queue.worker: 生成变体 1/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/models.py", line 836, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/models.py", line 758, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:17:23,859 [ERROR] app.services.queue.worker: 生成变体 2/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:17:24,172 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=230
2025-02-28 14:17:24,173 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_暂无图片-copy.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:17:24,174 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_暂无图片-copy.png
2025-02-28 14:17:24,177 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:17:24,345 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=233
2025-02-28 14:17:24,346 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_安卓数据线.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:17:24,346 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_安卓数据线.png
2025-02-28 14:17:24,350 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:17:24,359 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=231
2025-02-28 14:17:24,360 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-微信-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:17:24,360 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-微信-500.png
2025-02-28 14:17:24,361 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_973498d440494576a0e7a9ae2d9c532a, image_id=229
2025-02-28 14:17:24,361 [INFO] root: 找到缓存的图片: uploads/e3e35eec332acd63dfe79cc19ca49593.png
2025-02-28 14:17:24,361 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-谷歌浏览器-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:17:24,362 [INFO] app.services.queue.worker: 变体 2/3 生成成功: http://localhost:8002/uploads/e3e35eec332acd63dfe79cc19ca49593.png
2025-02-28 14:17:24,362 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-谷歌浏览器-500.png
2025-02-28 14:17:24,364 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:17:24,865 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=231
2025-02-28 14:17:24,873 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-微信-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:17:24,878 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-微信-500.png
2025-02-28 14:17:24,881 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:17:27,957 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:17:33,310 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:17:34,172 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:17:34,193 [ERROR] app.services.queue.worker: 生成变体 1/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:17:34,695 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=230
2025-02-28 14:17:34,696 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_暂无图片-copy.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:17:34,696 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_暂无图片-copy.png
2025-02-28 14:17:34,698 [INFO] root: 找到缓存的图片: uploads/1e059be7b940185608e8b1f9a2de8fa4.png
2025-02-28 14:17:34,698 [INFO] app.services.queue.worker: 变体 2/3 生成成功: http://localhost:8002/uploads/1e059be7b940185608e8b1f9a2de8fa4.png
2025-02-28 14:17:35,200 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=230
2025-02-28 14:17:35,202 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_暂无图片-copy.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:17:35,203 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_暂无图片-copy.png
2025-02-28 14:17:35,206 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:17:36,845 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:17:36,845 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:17:36,863 [ERROR] app.services.queue.worker: 生成变体 1/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:17:36,864 [ERROR] app.services.queue.worker: 生成变体 1/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:17:36,845 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:17:36,870 [ERROR] app.services.queue.worker: 生成变体 3/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:17:36,871 [INFO] app.services.queue.worker: 任务完成: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=232, 生成了 2 个变体
2025-02-28 14:17:36,874 [INFO] rq.worker: image_generation_6e0196a6925f408da6fbaba44187dbd4: Job OK (image_generation_6e0196a6925f408da6fbaba44187dbd4_232_e00a15b0da4d405ebd7d7295edf9c05f)
2025-02-28 14:17:36,874 [INFO] rq.worker: Result is kept for 500 seconds
2025-02-28 14:17:36,879 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-2-d32161e2: stopping on request
2025-02-28 14:17:36,879 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-2-d32161e2
2025-02-28 14:17:37,364 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=231
2025-02-28 14:17:37,365 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-微信-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:17:37,365 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-微信-500.png
2025-02-28 14:17:37,366 [INFO] app.services.queue.worker: 生成变体 2/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=229
2025-02-28 14:17:37,367 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-谷歌浏览器-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:17:37,367 [INFO] root: 找到缓存的图片: uploads/e3e35eec332acd63dfe79cc19ca49593.png
2025-02-28 14:17:37,367 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-谷歌浏览器-500.png
2025-02-28 14:17:37,368 [INFO] app.services.queue.worker: 变体 2/3 生成成功: http://localhost:8002/uploads/e3e35eec332acd63dfe79cc19ca49593.png
2025-02-28 14:17:37,369 [INFO] root: 找到缓存的图片: uploads/e3e35eec332acd63dfe79cc19ca49593.png
2025-02-28 14:17:37,369 [INFO] app.services.queue.worker: 变体 2/3 生成成功: http://localhost:8002/uploads/e3e35eec332acd63dfe79cc19ca49593.png
2025-02-28 14:17:37,869 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=231
2025-02-28 14:17:37,870 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-微信-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:17:37,870 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-微信-500.png
2025-02-28 14:17:37,871 [INFO] app.services.queue.worker: 生成变体 3/3: queue_id=image_generation_1ad9af0537c04c7481f3246d9ea75f08, image_id=229
2025-02-28 14:17:37,871 [INFO] root: 开始图像到图像生成 - 源图片: http://localhost:8002/uploads/projects/1/图标_icons8-谷歌浏览器-500.png, 提示词: 参考以上图片，保留图片中的整体风格，生成一张优化后的图片，生成的图片描述必须是英文，图片中的存在文字...
2025-02-28 14:17:37,871 [INFO] root: 转换为绝对路径: /Users/wangjunyan/image_project/backend/uploads/projects/1/图标_icons8-谷歌浏览器-500.png
2025-02-28 14:17:37,872 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:17:37,873 [INFO] root: 开始调用API生成图片 - 模型: black-forest-labs/FLUX-1-schnell
2025-02-28 14:17:37,989 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:17:43,335 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:17:45,207 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:17:45,222 [ERROR] app.services.queue.worker: 生成变体 3/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/image_project/backend/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:17:45,224 [INFO] app.services.queue.worker: 任务完成: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=230, 生成了 2 个变体
2025-02-28 14:17:45,226 [INFO] rq.worker: Successfully completed app.services.queue.worker.process_image_task({'image_id': 230, 'image_url': 'http://localhost:8002/uploads/projects/1/图标...) job in 0:09:59.968266s on worker wangjunyan.local:worker-1-d7cd041e
2025-02-28 14:17:45,227 [INFO] rq.worker: image_generation_6e0196a6925f408da6fbaba44187dbd4: Job OK (image_generation_6e0196a6925f408da6fbaba44187dbd4_230_6f302d420b0d4b80b8c92445092ac979)
2025-02-28 14:17:45,227 [INFO] rq.worker: Result is kept for 500 seconds
2025-02-28 14:17:45,231 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-d7cd041e: stopping on request
2025-02-28 14:17:45,231 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-d7cd041e
2025-02-28 14:17:48,020 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:17:49,882 [ERROR] root: 生成图片时发生错误: Task exceeded maximum timeout value (600 seconds)
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)
2025-02-28 14:17:49,913 [ERROR] app.services.queue.worker: 生成变体 3/3 失败: 
Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 649, in generate_image_to_image
    response = requests.post(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ' '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (600 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjunyan/image_project/backend/app/services/queue/worker.py", line 74, in process_image_task
    result = loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 760, in generate_image_to_image
    raise http_ex
  File "/Users/wangjunyan/image_project/backend/app/services/image_service.py", line 756, in generate_image_to_image
    raise HTTPException(status_code=400, detail=error_detail)
fastapi.exceptions.HTTPException

2025-02-28 14:17:49,915 [INFO] app.services.queue.worker: 任务完成: queue_id=image_generation_6e0196a6925f408da6fbaba44187dbd4, image_id=229, 生成了 2 个变体
2025-02-28 14:17:49,917 [INFO] rq.worker: image_generation_6e0196a6925f408da6fbaba44187dbd4: Job OK (image_generation_6e0196a6925f408da6fbaba44187dbd4_229_b8d2dc628a764db3a129ac8870e59d13)
2025-02-28 14:17:49,917 [INFO] rq.worker: Result is kept for 500 seconds
2025-02-28 14:17:49,921 [ERROR] rq.worker: Worker rq:worker:wangjunyan.local:worker-3-492a5981: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/worker.py", line 394, in work
    self.run_maintenance_tasks()
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/worker.py", line 530, in run_maintenance_tasks
    self.scheduler.acquire_locks(auto_start=True)
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/scheduler.py", line 113, in acquire_locks
    self.start()
  File "/Users/wangjunyan/GitLab/venv/lib/python3.9/site-packages/rq/scheduler.py", line 201, in start
    self._process.start()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
2025-02-28 14:17:49,924 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-3-492a5981
2025-02-28 14:17:50,840 [INFO] rq.worker: Killed horse pid 45369
2025-02-28 14:17:50,845 [WARNING] rq.worker: Moving job to FailedJobRegistry (Work-horse terminated unexpectedly; waitpid returned None; )
2025-02-28 14:17:50,848 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-3-782fc7c6: stopping on request
2025-02-28 14:17:50,848 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-3-782fc7c6
2025-02-28 14:17:53,361 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:17:58,053 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:18:03,386 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:18:08,080 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:18:13,420 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:18:18,107 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:18:23,277 [INFO] rq.worker: Killed horse pid 45938
2025-02-28 14:18:23,283 [WARNING] rq.worker: Moving job to FailedJobRegistry (Work-horse terminated unexpectedly; waitpid returned None; )
2025-02-28 14:18:23,285 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-5a41a425: stopping on request
2025-02-28 14:18:23,286 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-5a41a425
2025-02-28 14:18:23,447 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:18:23,948 [INFO] rq.worker: Killed horse pid 45942
2025-02-28 14:18:23,948 [INFO] rq.worker: Killed horse pid 45943
2025-02-28 14:18:23,948 [INFO] rq.worker: Killed horse pid 45944
2025-02-28 14:18:23,953 [WARNING] rq.worker: Moving job to FailedJobRegistry (Work-horse terminated unexpectedly; waitpid returned None; )
2025-02-28 14:18:23,953 [WARNING] rq.worker: Moving job to FailedJobRegistry (Work-horse terminated unexpectedly; waitpid returned None; )
2025-02-28 14:18:23,953 [WARNING] rq.worker: Moving job to FailedJobRegistry (Work-horse terminated unexpectedly; waitpid returned None; )
2025-02-28 14:18:23,955 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-d6ab93e2: stopping on request
2025-02-28 14:18:23,955 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-3-bdead76e: stopping on request
2025-02-28 14:18:23,955 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-2-a283659a: stopping on request
2025-02-28 14:18:23,956 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-2-a283659a
2025-02-28 14:18:23,956 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-d6ab93e2
2025-02-28 14:18:23,956 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-3-bdead76e
2025-02-28 14:18:28,132 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:18:33,476 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:18:34,300 [INFO] rq.worker: Killed horse pid 46112
2025-02-28 14:18:34,304 [WARNING] rq.worker: Moving job to FailedJobRegistry (Work-horse terminated unexpectedly; waitpid returned None; )
2025-02-28 14:18:34,307 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-7c6b6d25: stopping on request
2025-02-28 14:18:34,308 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-7c6b6d25
2025-02-28 14:18:36,967 [INFO] rq.worker: Killed horse pid 46146
2025-02-28 14:18:36,977 [WARNING] rq.worker: Moving job to FailedJobRegistry (Work-horse terminated unexpectedly; waitpid returned None; )
2025-02-28 14:18:36,979 [INFO] rq.worker: Killed horse pid 46147
2025-02-28 14:18:36,980 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-809967ea: stopping on request
2025-02-28 14:18:36,981 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-809967ea
2025-02-28 14:18:36,987 [WARNING] rq.worker: Moving job to FailedJobRegistry (Work-horse terminated unexpectedly; waitpid returned None; )
2025-02-28 14:18:36,989 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-3-ae27b7f5: stopping on request
2025-02-28 14:18:36,989 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-3-ae27b7f5
2025-02-28 14:18:38,158 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:18:43,505 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:18:48,178 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:18:53,529 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:18:58,200 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:19:03,560 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:19:08,229 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:19:13,588 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:19:18,254 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:19:23,619 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:19:28,288 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:19:33,649 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:19:38,314 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:19:43,673 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:19:48,337 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:19:53,698 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:19:58,366 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:20:03,719 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:20:08,398 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:20:13,740 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:20:18,420 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:20:23,765 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:20:28,446 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:20:33,791 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:20:38,470 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:20:43,817 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:20:48,498 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:20:53,846 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:20:58,525 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:21:03,870 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:21:08,553 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:21:13,899 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:21:14,597 [INFO] worker: 收到信号 15，关闭所有工作进程...
2025-02-28 14:21:14,598 [INFO] rq.worker: Worker wangjunyan.local:worker-3-a9396012 [PID 46720]: warm shut down requested
2025-02-28 14:21:14,598 [INFO] rq.worker: Worker wangjunyan.local:worker-1-2de8bec1 [PID 46718]: warm shut down requested
2025-02-28 14:21:14,598 [INFO] rq.worker: Worker wangjunyan.local:worker-2-770bd1d2 [PID 46719]: warm shut down requested
2025-02-28 14:21:14,600 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-2de8bec1
2025-02-28 14:21:14,600 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-3-a9396012
2025-02-28 14:21:14,600 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-2-770bd1d2
2025-02-28 14:21:14,774 [WARNING] rq.worker: Cold shut down
2025-02-28 14:21:14,775 [INFO] rq.worker: Killed horse pid 45368
2025-02-28 14:21:14,780 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-ef33b4f7
2025-02-28 14:21:15,050 [INFO] worker: 收到信号 15，关闭所有工作进程...
2025-02-28 14:21:15,051 [INFO] rq.worker: Worker wangjunyan.local:worker-1-3a6f5239 [PID 46647]: warm shut down requested
2025-02-28 14:21:15,053 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-3a6f5239
2025-02-28 14:21:17,938 [INFO] worker: 启动队列监控系统，并发工作进程数: 1
2025-02-28 14:21:17,964 [WARNING] worker: 未找到现有的图像生成队列，将监听默认队列
2025-02-28 14:21:17,964 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:21:17,964 [INFO] worker: 初始找到 2 个队列: default, image_generation_default
2025-02-28 14:21:17,967 [INFO] worker: 已启动工作进程 worker-1-4829a1f1 (PID: 59361)
2025-02-28 14:21:17,983 [INFO] worker: 发现 1 个新队列: image_generation_default
2025-02-28 14:21:17,983 [INFO] worker: 队列发生变化，重启所有工作进程以监听 1 个队列
2025-02-28 14:21:17,985 [INFO] worker: 已启动工作进程 worker-1-963599c3 (PID: 59362)
2025-02-28 14:21:18,044 [INFO] worker: 工作进程 worker-1-963599c3 (PID: 59362) 开始监听 1 个队列
2025-02-28 14:21:18,049 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-963599c3 started with PID 59362, version 2.1.0
2025-02-28 14:21:18,049 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-963599c3
2025-02-28 14:21:18,049 [INFO] rq.worker: *** Listening on image_generation_default...
2025-02-28 14:21:18,050 [ERROR] worker: 工作进程 worker-1-963599c3 (PID: 59362) 出错: daemonic processes are not allowed to have children
2025-02-28 14:21:28,013 [WARNING] worker: 工作进程 1 (PID: 59362) 已停止，重启中...
2025-02-28 14:21:28,014 [INFO] worker: 已重启工作进程 worker-1-dd3e519c (PID: 59541)
2025-02-28 14:21:28,081 [INFO] worker: 工作进程 worker-1-dd3e519c (PID: 59541) 开始监听 1 个队列
2025-02-28 14:21:28,085 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-dd3e519c started with PID 59541, version 2.1.0
2025-02-28 14:21:28,085 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-dd3e519c
2025-02-28 14:21:28,086 [INFO] rq.worker: *** Listening on image_generation_default...
2025-02-28 14:21:38,036 [INFO] worker: 发现 1 个新队列: image_generation_default:intermediate
2025-02-28 14:21:38,036 [INFO] worker: 有 1 个队列已移除: image_generation_default
2025-02-28 14:21:38,036 [INFO] worker: 清理 2 个旧worker注册信息
2025-02-28 14:21:38,036 [INFO] worker: 队列发生变化，重启所有工作进程以监听 1 个队列
2025-02-28 14:21:38,037 [INFO] rq.worker: Worker wangjunyan.local:worker-1-dd3e519c [PID 59541]: warm shut down requested
2025-02-28 14:21:38,037 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-dd3e519c
2025-02-28 14:21:38,156 [INFO] worker: 已启动工作进程 worker-1-3550daff (PID: 59672)
2025-02-28 14:21:38,228 [INFO] worker: 工作进程 worker-1-3550daff (PID: 59672) 开始监听 1 个队列
2025-02-28 14:21:38,231 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-3550daff started with PID 59672, version 2.1.0
2025-02-28 14:21:38,231 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-3550daff
2025-02-28 14:21:38,232 [INFO] rq.worker: *** Listening on image_generation_default:intermediate...
2025-02-28 14:21:38,232 [ERROR] worker: 工作进程 worker-1-3550daff (PID: 59672) 出错: daemonic processes are not allowed to have children
2025-02-28 14:21:48,183 [WARNING] worker: 工作进程 1 (PID: 59672) 已停止，重启中...
2025-02-28 14:21:48,185 [INFO] worker: 已重启工作进程 worker-1-1179c9cc (PID: 59840)
2025-02-28 14:21:48,264 [INFO] worker: 工作进程 worker-1-1179c9cc (PID: 59840) 开始监听 1 个队列
2025-02-28 14:21:48,267 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-1179c9cc started with PID 59840, version 2.1.0
2025-02-28 14:21:48,267 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-1179c9cc
2025-02-28 14:21:48,268 [INFO] rq.worker: *** Listening on image_generation_default:intermediate...
2025-02-28 14:21:48,269 [INFO] rq.worker: Cleaning registries for queue: image_generation_default:intermediate
2025-02-28 14:21:58,215 [INFO] worker: 发现 1 个新队列: image_generation_default:intermediate:intermediate
2025-02-28 14:21:58,215 [INFO] worker: 有 1 个队列已移除: image_generation_default:intermediate
2025-02-28 14:21:58,215 [INFO] worker: 清理 3 个旧worker注册信息
2025-02-28 14:21:58,215 [INFO] worker: 队列发生变化，重启所有工作进程以监听 1 个队列
2025-02-28 14:21:58,216 [INFO] rq.worker: Worker wangjunyan.local:worker-1-1179c9cc [PID 59840]: warm shut down requested
2025-02-28 14:21:58,216 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-1179c9cc
2025-02-28 14:21:58,333 [INFO] worker: 已启动工作进程 worker-1-e6a08bf7 (PID: 60003)
2025-02-28 14:21:58,394 [INFO] worker: 工作进程 worker-1-e6a08bf7 (PID: 60003) 开始监听 1 个队列
2025-02-28 14:21:58,397 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-e6a08bf7 started with PID 60003, version 2.1.0
2025-02-28 14:21:58,397 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-e6a08bf7
2025-02-28 14:21:58,398 [INFO] rq.worker: *** Listening on image_generation_default:intermediate:intermediate...
2025-02-28 14:21:58,398 [ERROR] worker: 工作进程 worker-1-e6a08bf7 (PID: 60003) 出错: daemonic processes are not allowed to have children
2025-02-28 14:22:08,362 [WARNING] worker: 工作进程 1 (PID: 60003) 已停止，重启中...
2025-02-28 14:22:08,363 [INFO] worker: 已重启工作进程 worker-1-679958ff (PID: 60174)
2025-02-28 14:22:08,434 [INFO] worker: 工作进程 worker-1-679958ff (PID: 60174) 开始监听 1 个队列
2025-02-28 14:22:08,438 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-679958ff started with PID 60174, version 2.1.0
2025-02-28 14:22:08,438 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-679958ff
2025-02-28 14:22:08,439 [INFO] rq.worker: *** Listening on image_generation_default:intermediate:intermediate...
2025-02-28 14:22:08,440 [INFO] rq.worker: Cleaning registries for queue: image_generation_default:intermediate:intermediate
2025-02-28 14:22:18,389 [INFO] worker: 发现 1 个新队列: image_generation_default:intermediate:intermediate:intermediate
2025-02-28 14:22:18,389 [INFO] worker: 有 1 个队列已移除: image_generation_default:intermediate:intermediate
2025-02-28 14:22:18,389 [INFO] worker: 清理 3 个旧worker注册信息
2025-02-28 14:22:18,390 [INFO] worker: 队列发生变化，重启所有工作进程以监听 1 个队列
2025-02-28 14:22:18,390 [INFO] rq.worker: Worker wangjunyan.local:worker-1-679958ff [PID 60174]: warm shut down requested
2025-02-28 14:22:18,391 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-679958ff
2025-02-28 14:22:18,503 [INFO] worker: 已启动工作进程 worker-1-096602b6 (PID: 60308)
2025-02-28 14:22:18,584 [INFO] worker: 工作进程 worker-1-096602b6 (PID: 60308) 开始监听 1 个队列
2025-02-28 14:22:18,588 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-096602b6 started with PID 60308, version 2.1.0
2025-02-28 14:22:18,588 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-096602b6
2025-02-28 14:22:18,588 [INFO] rq.worker: *** Listening on image_generation_default:intermediate:intermediate:intermediate...
2025-02-28 14:22:18,589 [ERROR] worker: 工作进程 worker-1-096602b6 (PID: 60308) 出错: daemonic processes are not allowed to have children
2025-02-28 14:22:28,525 [WARNING] worker: 工作进程 1 (PID: 60308) 已停止，重启中...
2025-02-28 14:22:28,526 [INFO] worker: 已重启工作进程 worker-1-9084e426 (PID: 60473)
2025-02-28 14:22:28,586 [INFO] worker: 工作进程 worker-1-9084e426 (PID: 60473) 开始监听 1 个队列
2025-02-28 14:22:28,589 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-9084e426 started with PID 60473, version 2.1.0
2025-02-28 14:22:28,589 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-9084e426
2025-02-28 14:22:28,590 [INFO] rq.worker: *** Listening on image_generation_default:intermediate:intermediate:intermediate...
2025-02-28 14:22:28,591 [INFO] rq.worker: Cleaning registries for queue: image_generation_default:intermediate:intermediate:intermediate
2025-02-28 14:22:38,566 [INFO] worker: 发现 1 个新队列: image_generation_default:intermediate:intermediate:intermediate:intermediate
2025-02-28 14:22:38,567 [INFO] worker: 有 1 个队列已移除: image_generation_default:intermediate:intermediate:intermediate
2025-02-28 14:22:38,567 [INFO] worker: 清理 3 个旧worker注册信息
2025-02-28 14:22:38,567 [INFO] worker: 队列发生变化，重启所有工作进程以监听 1 个队列
2025-02-28 14:22:38,569 [INFO] rq.worker: Worker wangjunyan.local:worker-1-9084e426 [PID 60473]: warm shut down requested
2025-02-28 14:22:38,572 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-9084e426
2025-02-28 14:22:38,655 [INFO] worker: 已启动工作进程 worker-1-f11a9387 (PID: 60647)
2025-02-28 14:22:38,737 [INFO] worker: 工作进程 worker-1-f11a9387 (PID: 60647) 开始监听 1 个队列
2025-02-28 14:22:38,740 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-f11a9387 started with PID 60647, version 2.1.0
2025-02-28 14:22:38,740 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-f11a9387
2025-02-28 14:22:38,741 [INFO] rq.worker: *** Listening on image_generation_default:intermediate:intermediate:intermediate:intermediate...
2025-02-28 14:22:38,741 [INFO] rq.worker: Cleaning registries for queue: image_generation_default:intermediate:intermediate:intermediate:intermediate
2025-02-28 14:22:38,838 [INFO] worker: 收到信号 15，关闭所有工作进程...
2025-02-28 14:22:38,839 [INFO] rq.worker: Worker wangjunyan.local:worker-1-f11a9387 [PID 60647]: warm shut down requested
2025-02-28 14:22:38,840 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-f11a9387
2025-02-28 14:22:41,641 [INFO] worker: 启动队列监控系统，并发工作进程数: 1
2025-02-28 14:22:41,666 [INFO] worker: 初始找到 1 个队列: image_generation_default:intermediate:intermediate:intermediate:intermediate:intermediate
2025-02-28 14:22:41,671 [INFO] worker: 已启动工作进程 worker-1-0ce9942e (PID: 60693)
2025-02-28 14:22:41,671 [INFO] worker: 启动了任务进度更新线程
2025-02-28 14:22:41,685 [INFO] worker: 发现 1 个新队列: image_generation_default:intermediate:intermediate:intermediate:intermediate:intermediate
2025-02-28 14:22:41,686 [INFO] worker: 队列发生变化，重启所有工作进程以监听 1 个队列
2025-02-28 14:22:41,687 [INFO] worker: 已启动工作进程 worker-1-7f33e9df (PID: 60694)
2025-02-28 14:22:41,744 [INFO] worker: 工作进程 worker-1-7f33e9df (PID: 60694) 开始监听 1 个队列
2025-02-28 14:22:41,747 [INFO] rq.worker: Worker rq:worker:wangjunyan.local:worker-1-7f33e9df started with PID 60694, version 2.1.0
2025-02-28 14:22:41,747 [INFO] rq.worker: Subscribing to channel rq:pubsub:wangjunyan.local:worker-1-7f33e9df
2025-02-28 14:22:41,750 [INFO] rq.worker: *** Listening on image_generation_default:intermediate:intermediate:intermediate:intermediate:intermediate...
2025-02-28 14:22:41,751 [INFO] rq.worker: Cleaning registries for queue: image_generation_default:intermediate:intermediate:intermediate:intermediate:intermediate
2025-02-28 14:22:51,710 [INFO] worker: 创建了默认图像生成队列: image_generation_default
2025-02-28 14:22:51,710 [INFO] worker: 发现 2 个新队列: image_generation_default, default
2025-02-28 14:22:51,710 [INFO] worker: 有 1 个队列已移除: image_generation_default:intermediate:intermediate:intermediate:intermediate:intermediate
2025-02-28 14:22:51,710 [INFO] worker: 清理 3 个旧worker注册信息
2025-02-28 14:22:51,710 [INFO] worker: 队列发生变化，重启所有工作进程以监听 2 个队列
2025-02-28 14:22:51,710 [INFO] rq.worker: Worker wangjunyan.local:worker-1-7f33e9df [PID 60694]: warm shut down requested
2025-02-28 14:22:51,711 [INFO] rq.worker: Unsubscribing from channel rq:pubsub:wangjunyan.local:worker-1-7f33e9df
2025-02-28 14:22:51,811 [INFO] worker: 已启动工作进程 worker-1-7c2a61fe (PID: 60917)
2025-02-28 14:23:01,837 [INFO] worker: 有 1 个队列已移除: default
2025-02-28 14:23:01,838 [INFO] worker: 清理 6 个旧worker注册信息
2025-02-28 14:23:01,838 [INFO] worker: 队列发生变化，重启所有工作进程以监听 1 个队列
2025-02-28 14:23:02,009 [INFO] worker: 已启动工作进程 worker-1-8c216202 (PID: 61098)
2025-02-28 14:23:51,544 [INFO] worker: 收到信号 15，关闭所有工作进程...
